### ISSUE TITLE
exit code 1 - rehydration error

### ISSUE THREAD

**Issue by lytt18** [ncbi/datasets#318] opened 2024-02-20 17:09 UTC
I'm running datasets rehydrate through an automated pipeline using Nextflow and I think it continued to rehydrate the rest of the files. However, the pipeline fails running during the rehydrate process with exit code 1.

The last message on stdout is: 
`Completed 43046 of 43049 [===============================================>] 100%`

I saw that there was an issue ( #198 ) that described something similar to what I'm experiencing. That issue was marked as resolved. Was there anything new implemented to address this behavior?

**Comment by ericcox1** [comment] 2024-02-20 17:52
Hi @lytt18,

Thanks for opening this issue. 

Please share the version of the client that you are using and the commands you used so that I can try to reproduce the issue.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by lytt18** [comment] 2024-02-20 18:29
I'm using version 16.3.0 and the command was: `datasets rehydrate --directory bacteria --max-workers 2`

**Comment by ericcox1** [comment] 2024-02-20 18:45
Thanks, could you please also provide the initial `download` command with any identifiers (taxonomic names, numeric identifiers, or assembly accessions) that you used? I'll need that to try to reproduce the issue.

>In relation to issue https://github.com/ncbi/datasets/issues/198 , were there any new flags/features to address this behavior?

I don't believe that we added any features because we were unable to reproduce the issue.

>The issue is likely what you said in https://github.com/ncbi/datasets/issues/198 about a filename change

If you could provide a file name or path that you think could be causing this that would help us to reproduce the issue and plan a fix.

**Comment by lytt18** [comment] 2024-02-20 19:44
Thanks for confirming that no new features were added in response to the earlier issue. 

The original datasets rehydrate command I sent was for a large query and I don't have a file name or path for the larger query that could have caused the error during rehydrate unfortunately. 

So, I'll just send a smaller example, where this issue was also observed in the same pipeline. The following genome accession was downloaded, decompressed, and (tried to) rehydrate. However, the error is not reproducible. I tried running this today manually and it worked. Here were the commands previously used that yielded the error originally.:

`datasets download genome accession GCF_000001405.40 --dehydrated --filename host.zip`
`datasets rehydrate --directory host --max-workers 2`

For automated environments like @bernt-matthias was describing, I agree that there should be a command line argument that allows to change the behavior:

- continue download and finish with exit code 1 (default)
- continue download and finish with exit code 0
- just stop and exit code 1

**Comment by ericcox1** [comment] 2024-02-21 15:55
Thank you for the feedback.  The client is designed to continue downloading whatever it can until every file has been attempted.  We will consider adding a flag to have a maximum number of errors, after which the CLI exits early.
However, we probably shouldn't alter the exit code and rely on the operating system to discard it.  You should be able to do this in unix environments with:
```
datasets rehydrate ... || echo "Rehydration failed for at least one file, but ignoring the error code"
```

I'm going to close this issue for now.

**Closed by ericcox1** 2024-02-21 15:55 UTC
Labels: enhancement
