### ISSUE TITLE
V1AssemblyDatasetDescriptor has no attribute 'biosample'

### ISSUE THREAD

**Issue by JDKling** [ncbi/datasets#114] opened 2022-04-25 19:36 UTC
I have been using GenomeApi to pull assembly accessions based on numeric taxonomic ids. My function was working as of a February of this year but I just started getting an error where "biosample" is being called and not finding an attribute with that name in V1AssemblyDatasetDescriptor. I am not using biosample IDs for anything so I am not sure where that is coming from. 

Here is the code causing the issue:
```
import ncbi.datasets.openapi
from ncbi.datasets.openapi.api import genome_api
from ncbi.datasets.openapi.model.v1_assembly_metadata_request_content_type import V1AssemblyMetadataRequestContentType
from ncbi.datasets.openapi.model.v1_assembly_metadata import V1AssemblyMetadata
from ncbi.datasets.openapi.model.v1_assembly_dataset_descriptors_filter_assembly_level import V1AssemblyDatasetDescriptorsFilterAssemblyLevel
from ncbi.datasets.openapi.model.rpc_status import RpcStatus
from ncbi.datasets.openapi.model.v1_assembly_dataset_descriptors_filter_assembly_source import V1AssemblyDatasetDescriptorsFilterAssemblySource

configuration = ncbi.datasets.openapi.Configuration(
    host = "https://api.ncbi.nlm.nih.gov/datasets/v1"
)

api_key = 'XXXXXXXXXXXXXXXXXXXX' 
configuration.api_key['ApiKeyAuthHeader'] = api_key

def get_stats(taxid_list):
        with ncbi.datasets.openapi.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            api_instance = genome_api.GenomeApi(api_client)


        for id in taxid_list:
            gen_calls = api_instance.assembly_descriptors_by_taxon(
                        taxon=id,
                        page_size = 1000)

taxid_list = ["375"] # Bradyrhizobium japonicum
get_stats(taxid_list)
```

Which gives a very long error but I will put the last few lines here:
```
ApiAttributeError: V1AssemblyDatasetDescriptor has no attribute 'biosample' at ['received_data']['assemblies'][0]['assembly']['biosample']
```

I am using python 3.9.6 and installed using `pip install ncbi-datasets-pylib`

Any insight here would be extremely helpful!

**Comment by ericcox1** [comment] 2022-04-25 21:58
Hi Joshua,

Thanks for opening this issue. Sorry to hear you're having trouble with the python library. We'll need a little more information to reproduce this bug. 
1. Could you explain what you're doing with `gen_calls`? 
2. Would you mind sharing the full text of the error?

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment] 2022-04-26 13:52
Hi Joshua, 

I have one other question. Could you please share what version of `ncbi-datasets-pylib` you are using?

-Eric

**Comment by JDKling** [comment] 2022-04-26 18:23
Thanks for responding so quickly! Basically I am just pulling accessions and assembly quality metrics (seq_length, contig_n50, etc...) for all genomes associated with a numeric taxonomic id (e.g. 375 for the bacterium Bradyrhizobium japonicum). 

The version I'm using i s 12.13.2 and here's a version of the above command with the parsing step for gen_calls

```
import pandas as pd
from collections import defaultdict, Counter

import ncbi.datasets.openapi
from ncbi.datasets.openapi.api import genome_api
from ncbi.datasets.openapi.model.v1_assembly_metadata_request_content_type import V1AssemblyMetadataRequestContentType
from ncbi.datasets.openapi.model.v1_assembly_metadata import V1AssemblyMetadata
from ncbi.datasets.openapi.model.v1_assembly_dataset_descriptors_filter_assembly_level import V1AssemblyDatasetDescriptorsFilterAssemblyLevel
from ncbi.datasets.openapi.model.rpc_status import RpcStatus
from ncbi.datasets.openapi.model.v1_assembly_dataset_descriptors_filter_assembly_source import V1AssemblyDatasetDescriptorsFilterAssemblySource

configuration = ncbi.datasets.openapi.Configuration(
    host = "https://api.ncbi.nlm.nih.gov/datasets/v1"
)

api_key = 'XXXXXXXXXXXXXXXX' 
configuration.api_key['ApiKeyAuthHeader'] = api_key

def get_stats(taxid_list):
        """Make a data frame of assembly stats for each genome found in a list 
        of numeric taxIDs"""
        with ncbi.datasets.openapi.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            api_instance = genome_api.GenomeApi(api_client)

        genome_data = defaultdict(list)
        found = set()

        for id in taxid_list:
            gen_calls = api_instance.assembly_descriptors_by_taxon(
                        taxon=id,
                        page_size = 1000)

            if gen_calls.assemblies is not None:
                for genome in gen_calls.assemblies:
                    if genome.assembly.assembly_accession not in found:
                        found.add(genome.assembly.assembly_accession)
                        genome_data['lookup name'].append(id)
                        genome_data['chromosome_count'].append(genome.assembly.chromosomes)
                        genome_data['accession'].append(genome.assembly.assembly_accession)
                        genome_data['contig_n50'].append(genome.assembly.contig_n50)
                        genome_data['seq_length'].append(genome.assembly.seq_length)
                        genome_data['category'].append(genome.assembly.assembly_category)
                        genome_data['name'].append(genome.assembly.display_name)
                        genome_data['date'].append(genome.assembly.submission_date)
                        genome_data['species'].append(genome.assembly.org.sci_name)
                        genome_data['strain'].append(genome.assembly.org.strain)
                        genome_data['tax_id'].append(genome.assembly.org.tax_id)

            else:
                print(f"Could not find any entries on NCBI for {id}")
            
            genome_data = pd.DataFrame(genome_data)
            return genome_data
```

and the full error (sorry it's a long one):

```
---------------------------------------------------------------------------
ApiAttributeError                         Traceback (most recent call last)
/var/folders/23/f5s338q51hs5w46y80_g2fkw0000gn/T/ipykernel_49134/3406039971.py in <module>
      1 taxid_list = ["375"] # Bradyrhizobium japonicum
----> 2 ncbi_genome_stats = get_stats(taxid_list)
      3 ncbi_genome_stats

/var/folders/23/f5s338q51hs5w46y80_g2fkw0000gn/T/ipykernel_49134/1408433764.py in get_stats(taxid_list)
     28 
     29         for id in taxid_list:
---> 30             gen_calls = api_instance.assembly_descriptors_by_taxon(
     31                         taxon=id,
     32                         page_size = 1000)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api_client.py in __call__(self, *args, **kwargs)
    769 
    770         """
--> 771         return self.callable(self, *args, **kwargs)
    772 
    773     def call_with_http_info(self, **kwargs):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api/genome_api.py in __assembly_descriptors_by_taxon(self, taxon, **kwargs)
    483             kwargs['taxon'] = \
    484                 taxon
--> 485             return self.call_with_http_info(**kwargs)
    486 
    487         self.assembly_descriptors_by_taxon = _Endpoint(

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api_client.py in call_with_http_info(self, **kwargs)
    831             params['header']['Content-Type'] = header_list
    832 
--> 833         return self.api_client.call_api(
    834             self.settings['endpoint_path'], self.settings['http_method'],
    835             params['path'],

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, async_req, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _check_type)
    406         """
    407         if not async_req:
--> 408             return self.__call_api(resource_path, method,
    409                                    path_params, query_params, header_params,
    410                                    body, post_params, files,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _check_type)
    221                 response_data.data = response_data.data.decode(encoding)
    222 
--> 223             return_data = self.deserialize(
    224                 response_data,
    225                 response_type,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/api_client.py in deserialize(self, response, response_type, _check_type)
    322         # store our data under the key of 'received_data' so users have some
    323         # context if they are deserializing a string and the data type is wrong
--> 324         deserialized_data = validate_and_convert_types(
    325             received_data,
    326             response_type,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in validate_and_convert_types(input_value, required_types_mixed, path_to_item, spec_property_naming, _check_type, configuration)
   1392         if configuration:
   1393             # if input_value is not valid_type try to convert it
-> 1394             converted_instance = attempt_convert_item(
   1395                 input_value,
   1396                 valid_classes,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in attempt_convert_item(input_value, valid_classes, path_to_item, configuration, spec_property_naming, key_type, must_convert, check_type)
   1279         try:
   1280             if issubclass(valid_class, OpenApiModel):
-> 1281                 return deserialize_model(input_value, valid_class,
   1282                                          path_to_item, check_type,
   1283                                          configuration, spec_property_naming)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in deserialize_model(model_data, model_class, path_to_item, check_type, configuration, spec_property_naming)
   1199     if isinstance(model_data, dict):
   1200         kw_args.update(model_data)
-> 1201         return model_class(**kw_args)
   1202     elif isinstance(model_data, PRIMITIVE_TYPES):
   1203         return model_class(model_data, **kw_args)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in wrapped_init(_self, *args, **kwargs)
   1575         if spec_property_naming:
   1576             kwargs = change_keys_js_to_python(kwargs, _self.__class__)
-> 1577         return fn(_self, *args, **kwargs)
   1578     return wrapped_init
   1579 

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model/v1_assembly_metadata.py in __init__(self, *args, **kwargs)
    180                 # discard variable.
    181                 continue
--> 182             setattr(self, var_name, var_value)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setattr__(self, attr, value)
    165     def __setattr__(self, attr, value):
    166         """set the value of an attribute using dot notation: `instance.attr = val`"""
--> 167         self[attr] = value
    168 
    169     def __getattr__(self, attr):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setitem__(self, name, value)
    350             return
    351 
--> 352         self.set_attribute(name, value)
    353 
    354     def get(self, name, default=None):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in set_attribute(self, name, value)
    137 
    138         if self._check_type:
--> 139             value = validate_and_convert_types(
    140                 value, required_types_mixed, path_to_item, self._spec_property_naming,
    141                 self._check_type, configuration=self._configuration)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in validate_and_convert_types(input_value, required_types_mixed, path_to_item, spec_property_naming, _check_type, configuration)
   1442             inner_path = list(path_to_item)
   1443             inner_path.append(index)
-> 1444             input_value[index] = validate_and_convert_types(
   1445                 inner_value,
   1446                 inner_required_types,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in validate_and_convert_types(input_value, required_types_mixed, path_to_item, spec_property_naming, _check_type, configuration)
   1392         if configuration:
   1393             # if input_value is not valid_type try to convert it
-> 1394             converted_instance = attempt_convert_item(
   1395                 input_value,
   1396                 valid_classes,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in attempt_convert_item(input_value, valid_classes, path_to_item, configuration, spec_property_naming, key_type, must_convert, check_type)
   1279         try:
   1280             if issubclass(valid_class, OpenApiModel):
-> 1281                 return deserialize_model(input_value, valid_class,
   1282                                          path_to_item, check_type,
   1283                                          configuration, spec_property_naming)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in deserialize_model(model_data, model_class, path_to_item, check_type, configuration, spec_property_naming)
   1199     if isinstance(model_data, dict):
   1200         kw_args.update(model_data)
-> 1201         return model_class(**kw_args)
   1202     elif isinstance(model_data, PRIMITIVE_TYPES):
   1203         return model_class(model_data, **kw_args)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in wrapped_init(_self, *args, **kwargs)
   1575         if spec_property_naming:
   1576             kwargs = change_keys_js_to_python(kwargs, _self.__class__)
-> 1577         return fn(_self, *args, **kwargs)
   1578     return wrapped_init
   1579 

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model/v1_assembly_match.py in __init__(self, *args, **kwargs)
    174                 # discard variable.
    175                 continue
--> 176             setattr(self, var_name, var_value)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setattr__(self, attr, value)
    165     def __setattr__(self, attr, value):
    166         """set the value of an attribute using dot notation: `instance.attr = val`"""
--> 167         self[attr] = value
    168 
    169     def __getattr__(self, attr):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setitem__(self, name, value)
    350             return
    351 
--> 352         self.set_attribute(name, value)
    353 
    354     def get(self, name, default=None):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in set_attribute(self, name, value)
    137 
    138         if self._check_type:
--> 139             value = validate_and_convert_types(
    140                 value, required_types_mixed, path_to_item, self._spec_property_naming,
    141                 self._check_type, configuration=self._configuration)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in validate_and_convert_types(input_value, required_types_mixed, path_to_item, spec_property_naming, _check_type, configuration)
   1392         if configuration:
   1393             # if input_value is not valid_type try to convert it
-> 1394             converted_instance = attempt_convert_item(
   1395                 input_value,
   1396                 valid_classes,

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in attempt_convert_item(input_value, valid_classes, path_to_item, configuration, spec_property_naming, key_type, must_convert, check_type)
   1279         try:
   1280             if issubclass(valid_class, OpenApiModel):
-> 1281                 return deserialize_model(input_value, valid_class,
   1282                                          path_to_item, check_type,
   1283                                          configuration, spec_property_naming)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in deserialize_model(model_data, model_class, path_to_item, check_type, configuration, spec_property_naming)
   1199     if isinstance(model_data, dict):
   1200         kw_args.update(model_data)
-> 1201         return model_class(**kw_args)
   1202     elif isinstance(model_data, PRIMITIVE_TYPES):
   1203         return model_class(model_data, **kw_args)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in wrapped_init(_self, *args, **kwargs)
   1575         if spec_property_naming:
   1576             kwargs = change_keys_js_to_python(kwargs, _self.__class__)
-> 1577         return fn(_self, *args, **kwargs)
   1578     return wrapped_init
   1579 

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model/v1_assembly_dataset_descriptor.py in __init__(self, *args, **kwargs)
    223                 # discard variable.
    224                 continue
--> 225             setattr(self, var_name, var_value)

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setattr__(self, attr, value)
    165     def __setattr__(self, attr, value):
    166         """set the value of an attribute using dot notation: `instance.attr = val`"""
--> 167         self[attr] = value
    168 
    169     def __getattr__(self, attr):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in __setitem__(self, name, value)
    350             return
    351 
--> 352         self.set_attribute(name, value)
    353 
    354     def get(self, name, default=None):

~/.virtualenvs/py3/lib/python3.9/site-packages/ncbi/datasets/openapi/model_utils.py in set_attribute(self, name, value)
    114             required_types_mixed = self.openapi_types[name]
    115         elif self.additional_properties_type is None:
--> 116             raise ApiAttributeError(
    117                 "{0} has no attribute '{1}'".format(
    118                     type(self).__name__, name),

ApiAttributeError: V1AssemblyDatasetDescriptor has no attribute 'biosample' at ['received_data']['assemblies'][0]['assembly']['biosample']
```

**Comment by ericcox1** [comment] 2022-04-27 13:43
> The version I'm using i s 12.13.2

Thanks Joshua. I discussed this with our development team and it looks like this bug is related to a schema change for biosample. This should be fixed in the latest version of the python library. We recommend updating `ncbi-datasets-pylib` to the latest version.

-Eric

**Closed** 2022-04-28 18:16 UTC
Labels: bug
